export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  STOCKTAKE_BATCH_NOT_FOUND: "STOCKTAKE_BATCH_NOT_FOUND",
  STOCKTAKE_PENDING_EXISTS: "STOCKTAKE_PENDING_EXISTS",
  STOCKTAKE_QUANTITY_INVALID: "STOCKTAKE_QUANTITY_INVALID",
  STOCKTAKE_SURPLUS_FORBIDDEN: "STOCKTAKE_SURPLUS_FORBIDDEN",
  STOCKTAKE_REASON_REQUIRED: "STOCKTAKE_REASON_REQUIRED",
  STOCKTAKE_ORDER_NOT_FOUND: "STOCKTAKE_ORDER_NOT_FOUND",
  STOCKTAKE_NOT_PENDING: "STOCKTAKE_NOT_PENDING",
  STOCKTAKE_APPROVAL_NOTE_REQUIRED: "STOCKTAKE_APPROVAL_NOTE_REQUIRED"
} as const;
