export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  STOCK_CHECK_DUPLICATE: "STOCK_CHECK_DUPLICATE",
  STOCK_CHECK_GAIN_BLOCKED: "STOCK_CHECK_GAIN_BLOCKED",
  STOCK_CHECK_NOT_PENDING: "STOCK_CHECK_NOT_PENDING"
} as const;
