spring:
  application:
    name: rescue-stock
  datasource:
    url: jdbc:h2:file:./data/rescue-stock;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health
